### PR TITLE
Update site landing page

### PR DESCRIPTION
**Pull request by vicchi**
This should now reflect the current set of providers across the main and extras project

### CODE REVIEW

**Comment by vicchi** [comment]
@willdurand - the Travis build is having exactly the same problems installing as I was on my local machine. Are you able to get a working Jekyll build up and running to test this?

**Comment by vicchi** [comment]
This looks like the source of the issue - https://github.com/blog/2100-github-pages-jekyll-3

tl;dr - redcarpet support has been obsoleted and replaced with kramdown for Markdown rendering.

Sure enough, modifying the site's `_config.yml` to use `kramdown` seems to work, but there's some warnings from Jekyll 3 which I want to tidy up first.

Watch this space

**Comment by vicchi** [comment]
@willdurand Fixed the site build issues and upgraded to support Jekyll 3.0. All building cleanly now. Could you take a look at this PR and merge please?

**Comment by willdurand** [comment]
Awesome! ❤️

**Pull request merged**
